use crate::android::backend::wayland::{
    input::{
        RelativePosition, WinitInput, WinitKeyboardInputEvent, WinitMouseInputEvent,
        WinitMouseMovedEvent, WinitMouseWheelEvent, WinitTouchCancelledEvent, WinitTouchEndedEvent,
        WinitTouchMovedEvent, WinitTouchStartedEvent,
    },
    keymap::physicalkey_to_scancode,
    TouchMode, WaylandBackend,
};
use crate::android::utils::ndk;
use smithay::backend::input::InputEvent;
use smithay::utils::{Physical, Size};
use winit::dpi::PhysicalPosition;
use winit::event::{ElementState, MouseScrollDelta, Touch, TouchPhase, WindowEvent};

/// Specific events generated by Winit
#[derive(Debug)]
pub enum CentralizedEvent {
    /// The window has been resized
    Resized {
        /// The new physical size (in pixels)
        size: Size<i32, Physical>,
        guest_scale_factor: f64,
    },

    /// The focus state of the window changed
    Focus(bool),

    /// An input event occurred.
    Input(InputEvent<WinitInput>),

    /// The user requested to close the window.
    CloseRequested,

    /// A redraw was requested
    Redraw,

    /// TODO: Support these events
    Unsupported,
}

fn centralize_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    match state {
        ElementState::Pressed => backend.key_counter += 1,
        ElementState::Released => {
            backend.key_counter = backend.key_counter.saturating_sub(1);
        }
    };

    let event = InputEvent::Keyboard {
        event: WinitKeyboardInputEvent {
            time,
            key: scancode,
            count: backend.key_counter,
            state,
        },
    };
    CentralizedEvent::Input(event)
}

pub fn centralize_injected_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    centralize_keyboard(scancode, state, time, backend)
}

pub fn centralize(event: WindowEvent, backend: &mut WaylandBackend) -> CentralizedEvent {
    let time = backend.clock.now().as_millis() as u64;
    return match event {
        WindowEvent::Resized(size) => {
            let (w, h): (i32, i32) = size.into();
            backend.guest_scale_factor = ndk::scale_factor(&backend.android_app);

            CentralizedEvent::Resized {
                size: (w, h).into(),
                guest_scale_factor: backend.guest_scale_factor,
            }
        }
        WindowEvent::ScaleFactorChanged { .. } => {
            backend.guest_scale_factor = ndk::scale_factor(&backend.android_app);
            let (w, h): (i32, i32) = backend
                .graphic_renderer
                .as_ref()
                .unwrap()
                .window()
                .inner_size()
                .into();
            CentralizedEvent::Resized {
                size: (w, h).into(),
                guest_scale_factor: backend.guest_scale_factor,
            }
        }
        WindowEvent::RedrawRequested => CentralizedEvent::Redraw,
        WindowEvent::CloseRequested => CentralizedEvent::CloseRequested,
        WindowEvent::Focused(focused) => CentralizedEvent::Focus(focused),
        WindowEvent::KeyboardInput {
            event,
            is_synthetic,
            ..
        } if !is_synthetic && !event.repeat => {
            let scancode = physicalkey_to_scancode(event.physical_key).unwrap_or(0);
            centralize_keyboard(scancode, event.state, time, backend)
        }
        WindowEvent::CursorMoved { position, .. } => {
            let event = InputEvent::PointerMotionAbsolute {
                event: WinitMouseMovedEvent {
                    time,
                    position: relative_position(backend, position),
                    global_position: position,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::MouseWheel { delta, .. } => {
            let event = InputEvent::PointerAxis {
                event: WinitMouseWheelEvent { time, delta },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::MouseInput { state, button, .. } => {
            let event = InputEvent::PointerButton {
                event: WinitMouseInputEvent {
                    time,
                    button,
                    state,
                    is_x11: false,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Started,
            location,
            id,
            ..
        }) => {
            backend.touch_points.insert(id, location);
            backend.scroll_centroid = Some(centroid(&backend.touch_points));

            if backend.touch_points.len() >= 2 {
                // A second finger is unambiguously a scroll, whatever the first one was doing.
                backend.touch_mode = TouchMode::Scroll;
                return CentralizedEvent::Unsupported;
            }

            backend.touch_mode = TouchMode::Undecided;
            backend.touch_down_position = Some(location);
            backend.touch_down_time = Some(time);
            CentralizedEvent::Input(InputEvent::TouchDown {
                event: WinitTouchStartedEvent {
                    time,
                    global_position: location,
                    position: relative_position(backend, location),
                    id,
                },
            })
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Moved,
            location,
            id,
            ..
        }) => {
            backend.touch_points.insert(id, location);

            if backend.touch_mode == TouchMode::Undecided && travelled_past_slop(backend, location)
            {
                backend.touch_mode = TouchMode::Scroll;
                // Start scrolling from here, so the slop the finger just used up doesn't
                // arrive as one jump.
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
            }
            if backend.touch_mode == TouchMode::LongPress && travelled_past_slop(backend, location)
            {
                backend.touch_mode = TouchMode::Drag;
            }

            match backend.touch_mode {
                // Still deciding between a tap, a scroll and a long press: don't move the
                // cursor yet, or a scroll would drag it along.
                TouchMode::Undecided | TouchMode::LongPress => CentralizedEvent::Unsupported,
                TouchMode::Scroll => {
                    // Scroll by the centroid delta, which is the finger itself when only one
                    // is down. Positive axis values scroll the view down, so the raw delta
                    // (negated once more in `WinitMouseWheelEvent::amount`) makes the content
                    // follow the finger the way Android does.
                    let new_centroid = centroid(&backend.touch_points);
                    let last = backend.scroll_centroid.replace(new_centroid);
                    let Some(last) = last else {
                        return CentralizedEvent::Unsupported;
                    };
                    let dx = new_centroid.x - last.x;
                    let dy = new_centroid.y - last.y;
                    if dx == 0.0 && dy == 0.0 {
                        return CentralizedEvent::Unsupported;
                    }
                    CentralizedEvent::Input(InputEvent::PointerAxis {
                        event: WinitMouseWheelEvent {
                            time,
                            delta: MouseScrollDelta::PixelDelta(PhysicalPosition { x: dx, y: dy }),
                        },
                    })
                }
                TouchMode::Drag => CentralizedEvent::Input(InputEvent::TouchMotion {
                    event: WinitTouchMovedEvent {
                        time,
                        position: relative_position(backend, location),
                        global_position: location,
                        id,
                    },
                }),
            }
        }

        WindowEvent::Touch(Touch {
            phase: TouchPhase::Ended,
            location,
            id,
            ..
        }) => {
            backend.touch_points.remove(&id);
            if !backend.touch_points.is_empty() {
                // Don't forward a stray TouchUp while other fingers are still down; re-anchor
                // the centroid so the remaining fingers don't jump the scroll.
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
                return CentralizedEvent::Unsupported;
            }

            let mode = backend.touch_mode;
            backend.reset_touch_state();
            CentralizedEvent::Input(InputEvent::TouchUp {
                event: WinitTouchEndedEvent {
                    time,
                    id,
                    mode,
                    x: location.x,
                    y: location.y,
                },
            })
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Cancelled,
            id,
            ..
        }) => {
            backend.touch_points.remove(&id);
            if !backend.touch_points.is_empty() {
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
                return CentralizedEvent::Unsupported;
            }

            backend.reset_touch_state();
            CentralizedEvent::Input(InputEvent::TouchCancel {
                event: WinitTouchCancelledEvent { time, id },
            })
        }

        _ => {
            log::info!("Unhandled event: {:?}", event);
            CentralizedEvent::Unsupported
        }
    };
}

/// Normalize a window-relative pixel position into the 0..1 range the input backend expects.
fn relative_position(
    backend: &WaylandBackend,
    location: PhysicalPosition<f64>,
) -> RelativePosition {
    let size = backend
        .graphic_renderer
        .as_ref()
        .unwrap()
        .window()
        .inner_size();
    RelativePosition::new(
        location.x / size.width as f64,
        location.y / size.height as f64,
    )
}

/// Whether the finger has moved far enough from where it landed to stop being a tap.
fn travelled_past_slop(backend: &WaylandBackend, location: PhysicalPosition<f64>) -> bool {
    backend
        .touch_down_position
        .map(|start| {
            let dx = location.x - start.x;
            let dy = location.y - start.y;
            dx * dx + dy * dy > backend.touch_slop_px * backend.touch_slop_px
        })
        .unwrap_or(false)
}

fn centroid(
    points: &std::collections::HashMap<u64, PhysicalPosition<f64>>,
) -> PhysicalPosition<f64> {
    let n = points.len() as f64;
    let (sx, sy) = points
        .values()
        .fold((0.0, 0.0), |(sx, sy), p| (sx + p.x, sy + p.y));
    PhysicalPosition {
        x: sx / n,
        y: sy / n,
    }
}
